/**
 * Phase 15.0.f — Export reports (JSON / Markdown).
 *
 * Trigger download bằng cách tạo Blob + temporary anchor click — work
 * cả trong Tauri WebView (file → user Downloads) và browser dev mode.
 *
 * Markdown format human-readable, paste vào Slack/Notion/email được luôn.
 */

import { saveReport, type SysReport, type BenchResult } from '../tauri-bridge.js';
import { formatBytes, formatUptime } from '../scoring.js';

export interface ExportPayload {
  sys: SysReport;
  cpu_bench: BenchResult | null;
  mem_bench: BenchResult | null;
  generated_at: string;
  app_version: string;
}

// ============================================================
// JSON
// ============================================================

export function buildJsonReport(payload: ExportPayload): string {
  return JSON.stringify(payload, null, 2);
}

// ============================================================
// Markdown
// ============================================================

export function buildMarkdownReport(payload: ExportPayload): string {
  const { sys, cpu_bench, mem_bench, generated_at, app_version } = payload;

  const lines: string[] = [];
  lines.push('# Báo cáo TrishCheck');
  lines.push('');
  lines.push(`Generated: \`${generated_at}\``);
  lines.push(`Tool: TrishCheck v${app_version}`);
  lines.push('');

  // System
  lines.push('## Thông tin máy');
  lines.push('');
  lines.push('| Mục | Giá trị |');
  lines.push('| --- | --- |');
  lines.push(`| Hệ điều hành | ${sys.os} ${sys.os_version} |`);
  lines.push(`| Kiến trúc | ${sys.arch} |`);
  lines.push(`| Tên máy | ${sys.hostname} |`);
  lines.push(`| Uptime | ${formatUptime(sys.uptime_seconds)} |`);
  lines.push(`| CPU | ${sys.cpu_brand} |`);
  lines.push(`| Số nhân | ${sys.cpu_cores} |`);
  lines.push(
    `| Xung nhịp | ${
      sys.cpu_freq_mhz ? `${(sys.cpu_freq_mhz / 1000).toFixed(2)} GHz` : '—'
    } |`,
  );
  lines.push(`| RAM tổng | ${formatBytes(sys.total_memory_bytes)} |`);
  lines.push(`| RAM đang dùng | ${formatBytes(sys.used_memory_bytes)} |`);
  lines.push(`| Swap | ${formatBytes(sys.total_swap_bytes)} |`);
  lines.push('');

  // Disks
  if (sys.disks.length > 0) {
    lines.push('## Ổ đĩa');
    lines.push('');
    lines.push('| Ổ | Mount | FS | Tổng | Còn trống | Removable |');
    lines.push('| --- | --- | --- | --- | --- | --- |');
    for (const d of sys.disks) {
      lines.push(
        `| ${d.name || '—'} | ${d.mount_point} | ${d.file_system} | ${formatBytes(
          d.total_bytes,
        )} | ${formatBytes(d.available_bytes)} | ${d.is_removable ? '✓' : '—'} |`,
      );
    }
    lines.push('');
  }

  // Network
  if (sys.networks.length > 0) {
    lines.push('## Mạng');
    lines.push('');
    lines.push('| Adapter | MAC | RX | TX |');
    lines.push('| --- | --- | --- | --- |');
    for (const n of sys.networks) {
      lines.push(
        `| ${n.name} | \`${n.mac_address}\` | ${formatBytes(n.received_bytes)} | ${formatBytes(n.transmitted_bytes)} |`,
      );
    }
    lines.push('');
  }

  // Benchmark
  if (cpu_bench || mem_bench) {
    lines.push('## Benchmark');
    lines.push('');
    if (cpu_bench) {
      lines.push(
        `- **CPU (SHA-256)**: ${cpu_bench.throughput_mb_per_s.toFixed(0)} MB/s (${formatBytes(
          cpu_bench.bytes_processed,
        )} trong ${cpu_bench.elapsed_ms} ms)`,
      );
    }
    if (mem_bench) {
      lines.push(
        `- **Memory bandwidth**: ${mem_bench.throughput_mb_per_s.toFixed(0)} MB/s (${formatBytes(
          mem_bench.bytes_processed,
        )} trong ${mem_bench.elapsed_ms} ms)`,
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [TrishCheck](https://trishteam.io.vn)*');

  return lines.join('\n');
}

// ============================================================
// Save report — Rust-side write to Downloads folder
// ============================================================

export type ExportFormat = 'json' | 'md';

/**
 * Build content + lưu file. Trả full path đã lưu (vd
 * `C:\Users\TRI\Downloads\trishcheck-report-2026-04-25T12-34-56.json`).
 * Caller hiện toast confirm với path.
 */
export async function downloadReport(
  payload: ExportPayload,
  format: ExportFormat,
): Promise<string> {
  const content =
    format === 'json'
      ? buildJsonReport(payload)
      : buildMarkdownReport(payload);

  const ext = format === 'json' ? 'json' : 'md';
  const ts = payload.generated_at.replace(/[:.]/g, '-').slice(0, 19);
  const filename = `trishcheck-report-${ts}.${ext}`;

  return saveReport(filename, content);
}
